# Generated by Django 4.1 on 2022-08-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
